# Generated by Django 3.2.12 on 2022-04-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_crypto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
